export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const RESTORE_AUTH = 'RESTORE_AUTH';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const SEND_EMAIL_RESET_PASSWORD = 'SEND_EMAIL_RESET_PASSWORD';
export const GET_INFO_RESET_PASSWORD = 'GET_INFO_RESET_PASSWORD';
export const SEND_NEW_PASSWORD = 'SEND_NEW_PASSWORD';
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const SET_SCREEN_MODE = 'SET_SCREEN_MODE';
export const GET_USERS = 'GET_USERS';
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS';
export const RESPONSE_ERROR = 'RESPONSE_ERROR';
export const SEND_REQUEST = 'SEND_REQUEST';
export const GET_DOCS = 'GET_DOCS';
export const CREATE_DOC = 'CREATE_DOC';
export const SET_FILES = 'SET_FILES';
export const DELETE_TMP_FILE = 'DELETE_TMP_FILE';
export const UPLOAD_TMP_FILE = 'UPLOAD_TMP_FILE';
export const DELETE_FILE = 'DELETE_FILE';
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const CLEAR_UPLOADER_FILES = 'CLEAR_UPLOADER_FILES';
export const CLOSE_POPUP_UPLOAD_DOCS = 'CLOSE_POPUP_UPLOAD_DOCS';
export const OPEN_POPUP_UPLOAD_DOCS = 'OPEN_POPUP_UPLOAD_DOCS';

export const startAction = type => `START_${type}`;
export const successAction = type => `SUCCESS_${type}`;
export const failAction = type => `FAIL_${type}`;
